# Generated by Django 4.0.2 on 2022-02-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='humidity',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='moisture',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='temperature',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
